[debug] [2020-04-16T17:32:55.711Z] ----------------------------------------------------------------------
[debug] [2020-04-16T17:32:55.714Z] Command:       /Users/jriley/.nvm/versions/node/v10.15.0/bin/node /Users/jriley/.nvm/versions/node/v10.15.0/bin/firebase init
[debug] [2020-04-16T17:32:55.715Z] CLI Version:   8.0.3
[debug] [2020-04-16T17:32:55.715Z] Platform:      darwin
[debug] [2020-04-16T17:32:55.715Z] Node Version:  v10.15.0
[debug] [2020-04-16T17:32:55.716Z] Time:          Thu Apr 16 2020 13:32:55 GMT-0400 (Eastern Daylight Time)
[debug] [2020-04-16T17:32:55.716Z] ----------------------------------------------------------------------
[debug] [2020-04-16T17:32:55.716Z] 
[debug] [2020-04-16T17:32:55.732Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-04-16T17:32:55.927Z] Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (/Users/jriley/.nvm/versions/node/v10.15.0/lib/node_modules/firebase-tools/node_modules/google-auth-library/build/src/auth/googleauth.js:160:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[error] 
[error] Error: An unexpected error has occurred.
